version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk  # Base image with JDK
    steps:
      - checkout
      - run:
          name: Update Package List
          command: sudo apt-get update  # This updates the package lists
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven
      - run:
          name: Verify Maven Installation
          command: mvn -v
      - run:
          name: Build with Maven
          command: mvn clean install
