version: 2.1

jobs:
  build:
    docker:
      - image: eclipse-temurin:11-jdk  # CircleCI's OpenJDK image
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
