version: 2.1

jobs:
  build:
    docker:
      - image: eclipse-temurin:11-jdk  # CircleCI's OpenJDK image
    steps:
      - checkout
      - run:
          name: Update Package List
          command: sudo apt-get update
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven
      - run:
          name: Verify Maven Installation
          command: mvn -v
      - run:
          name: Build with Maven
          command: mvn clean install
