version: 2.1

jobs:
  say-hello:

    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
        name: "Install Maven"
        command: sudo apt-get install -y maven

      - run:
          name: "Say hello"
          command: "echo Hello, World!"

      - run:
          name: "Run Tests"
          command: mvn test

workflows:
  say-hello-workflow:
    jobs:
      - say-hello